name: travel_app
description: Travel App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/images/profile/
    - assets/images/visit/
    - assets/images/offers/
    - assets/images/upcoming/
    - assets/images/nature/
    - assets/images/landmark/
    - assets/images/nearby/
    - assets/images/detailcover/
    - assets/images/icons/


